MA-06
beevasya/MathAppNew pull request #37
Opened 2023-12-19 09:09 UTC by Pail4

2023-12-19 09:09 UTC, Pail4 commented
Потрачено: 10 минут

2023-12-19 09:13 UTC, beevasya requested changes
Вы выполнили не ту задачу, я говорил что нужно взять две задачи, при этом одна из задач должна быть с проверкой. В таких задача так и написано "с проверкой"

2023-12-19 11:38 UTC, Pail4 commented
@beevasya, Ну, я подумал, что "проверка" это ваше код-ревью. В любом случае, в этой задаче тоже есть проверка
![image](https://github.com/beevasya/MathAppNew/assets/73517684/eaff6d82-ce8c-4644-9aab-6819d1d003e0)

Можно я не буду делать третью задачу, пожалуйста?

2023-12-20 06:32 UTC, beevasya approved these changes
Ладно, пусть будет

2023-12-20 10:59 UTC, merged